{% set name = "redistpy" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redistpy-{{ version }}.tar.gz
  sha256: 00060200f62de6f92c07502502138539505ca80634edf9e1752a1048c46db9a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.26
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema
    - matplotlib-base
    - numpy
    - scipy
    - pyhf
    - requests
    - numexpr
    - iminuit
    - jinja2
    - ipykernel

test:
  imports:
    - redist
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Package for reinterpretation of particle physics results
  license: MIT
  license_file: LICENSE
  home: https://github.com/lorenzennio/redist

extra:
  recipe-maintainers:
    - lorenzennio
